version: '3'

services:
  etcd-1:
    image: quay.io/coreos/etcd:latest
    entrypoint: /usr/local/bin/etcd
    networks:
      etcd_net:
        ipv4_address: ${ETCD_01_ADDRESS}
    command:
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://${ETCD_01_ADDRESS}:2380'
      - '--listen-peer-urls=http://${ETCD_01_ADDRESS}:2380'
      - '--listen-client-urls=http://${ETCD_01_ADDRESS}:2379,http://localhost:2379'
      - '--advertise-client-urls=http://${ETCD_01_ADDRESS}:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://${ETCD_01_ADDRESS}:2380,etcd-2=http://${ETCD_02_ADDRESS}:2380,etcd-3=http://${ETCD_03_ADDRESS}:2380'
      - '--initial-cluster-state=new'

  etcd-2:
    image: quay.io/coreos/etcd:latest
    entrypoint: /usr/local/bin/etcd
    networks:
      etcd_net:
        ipv4_address: ${ETCD_02_ADDRESS}
    command:
      - '--name=etcd-2'
      - '--initial-advertise-peer-urls=http://${ETCD_02_ADDRESS}:2380'
      - '--listen-peer-urls=http://${ETCD_02_ADDRESS}:2380'
      - '--listen-client-urls=http://${ETCD_02_ADDRESS}:2379,http://localhost:2379'
      - '--advertise-client-urls=http://${ETCD_02_ADDRESS}:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://${ETCD_01_ADDRESS}:2380,etcd-2=http://${ETCD_02_ADDRESS}:2380,etcd-3=http://${ETCD_03_ADDRESS}:2380'
      - '--initial-cluster-state=new'

  etcd-3:
    image: quay.io/coreos/etcd:latest
    entrypoint: /usr/local/bin/etcd
    networks:
      etcd_net:
        ipv4_address: ${ETCD_03_ADDRESS}
    command:
      - '--name=etcd-3'
      - '--initial-advertise-peer-urls=http://${ETCD_03_ADDRESS}:2380'
      - '--listen-peer-urls=http://${ETCD_03_ADDRESS}:2380'
      - '--listen-client-urls=http://${ETCD_03_ADDRESS}:2379,http://localhost:2379'
      - '--advertise-client-urls=http://${ETCD_03_ADDRESS}:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://${ETCD_01_ADDRESS}:2380,etcd-2=http://${ETCD_02_ADDRESS}:2380,etcd-3=http://${ETCD_03_ADDRESS}:2380'
      - '--initial-cluster-state=new'

networks:
  etcd_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${ETCD_SUBNET}
